language: java
before_script:
- "cd BibLexRefManager"

notifications:
  irc: 
   channels:
      - "irc.cc.tut.fi#cyborgducks"
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
