language: java
before_script:
- "cd BibLexRefManager"

after_success:
  - mvn clean cobertura:cobertura coveralls:report

notifications:
  irc:
    channels:
      - "irc.cc.tut.fi#cyborgducks"
    template:
      - "%{repository} (%{commit}) : %{message}"
      - "Build details: %{build_url}"
deploy:
  provider: releases
  api_key: auth
  file: "BibLexRefManager/target/BibLexRefManager-*.jar"
  skip_cleanup: true
  on:
    tags: true